image: node:4.2.2

pages:
  cache:
    paths:
      - node_modules/

  script:
    - npm update
    - npm ci
    - npm run build
    - mv ./build ./public
  artifacts:
    paths:
      - public
  only:
    - master
