image: node:latest

pages:
  cache:
    paths:
      - node_modules/

  script:
    - npm ci
    - npm run build
    - rmdir ./public
    - mv ./build ./public
  artifacts:
    paths:
      - public
  only:
    - master
